FROM python:3.12-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY poetry.lock pyproject.toml /app/
RUN pip install poetry && poetry config virtualenvs.create false && poetry install --no-dev

COPY . /app/

CMD ["poetry", "run", "gunicorn", "databrary.wsgi:application", "--bind", "0.0.0.0:8000"]
